-- Power BI query shape 53 of 663, from workspace_jf.landscape.qh.
-- Not a schema probe: this shape reads data and returns rows.
--
-- Executions            1,753
-- Distinct texts        1 (same query, different literals or projection)
-- Rows read             108,749,401
-- Rows returned         101,737
-- Avg duration          3,219 ms
-- Power BI datasets     3fdd5aed-f1c1-47e1-b7b0-5d4b81493a8d, aa36e346-e2cc-4210-a366-8c48278fcdbd, b19514eb-b858-44d5-81a1-2c1a2e9f1483
-- Tables                prod_homecare_actransactional_homecare.referral, prod_homecare_actransactional_organization.org, prod_homecare_actransactional_organization.provider
--
-- Power BI's `SELECT ... FROM (...) AS `_`` envelope was stripped, so this
-- is the inner query as written, reformatted by sqlglot -- not the exact
-- bytes Power BI sent.

SELECT DISTINCT
  o.*
FROM prod_homecare_actransactional_organization.org AS o
RIGHT JOIN (
  SELECT DISTINCT
    p.*,
    CASE
      WHEN Name LIKE '%123 Home Care%'
      THEN '123 Home Care'
      WHEN Name LIKE '%1Heart Caregiver Services%'
      THEN '1Heart Caregiver Services'
      WHEN Name LIKE '%2nd Family%'
      THEN '2nd Family'
      WHEN Name LIKE '%A Better Solution%'
      THEN 'A Better Solution'
      WHEN Name LIKE '%A Homemade Plan%'
      THEN 'A Homemade Plan'
      WHEN Name LIKE '%Acasa%'
      THEN 'Acasa'
      WHEN Name LIKE '%Advocate In-Home Care%'
      THEN 'Advocate In-Home Care'
      WHEN Name LIKE '%Age in Place%'
      THEN 'Age in Place'
      WHEN Name LIKE '%Alegre Home Care%'
      THEN 'Alegre Home Care'
      WHEN Name LIKE '%All Ways Caring%'
      THEN 'All Ways Caring'
      WHEN Name LIKE '%24 Hour Home Care%'
      THEN '24 Hour Home Care'
      WHEN Name LIKE '%A Caring Hand Services%'
      THEN 'A Caring Hand'
      WHEN Name LIKE '%A Hand to Hold%'
      THEN 'A Hand to Hold'
      WHEN Name LIKE '%A Place at Home%'
      THEN 'A Place at Home'
      WHEN Name LIKE '%AccentCare%'
      THEN 'AccentCare'
      WHEN Name LIKE '%AccordCare%'
      THEN 'AccordCare'
      WHEN Name LIKE '%Acti-Kare%'
      THEN 'Acti-Kare'
      WHEN Name LIKE '%Acti Kare%'
      THEN 'Acti-Kare'
      WHEN Name LIKE '%AdvisaCare%'
      THEN 'AdvisaCare'
      WHEN Name LIKE '%Addus Home Care%'
      THEN 'Addus Home Care'
      WHEN Name LIKE '%Affordable Home Care%'
      THEN 'Affordable Home Care'
      WHEN Name LIKE '%Affordable HomeCare%'
      THEN 'Affordable Home Care'
      WHEN Name LIKE '%Allegiant Home Care%'
      THEN 'Allegiant Home Care'
      WHEN Name LIKE '%Always Best Care %'
      THEN 'Always Best Care'
      WHEN Name LIKE '%Amada Senior Care%'
      THEN 'Amada Senior Care'
      WHEN Name LIKE '%American In-Home Care%'
      THEN 'American In-Home Care'
      WHEN Name LIKE '%AmeriCare%'
      THEN 'Americare'
      WHEN Name LIKE '%Arosa%'
      THEN 'Arosa'
      WHEN Name LIKE '%Assisting Hands%'
      THEN 'Assisting Hands Home Care'
      WHEN Name LIKE '%At Home Eldercare%'
      THEN 'At Home Eldercare'
      WHEN Name LIKE '%Bright Star%'
      THEN 'BrightStar Care'
      WHEN Name LIKE '%BrightStar%'
      THEN 'BrightStar Care'
      WHEN Name LIKE '%Care Advantage%'
      THEN 'Care Advantage'
      WHEN Name LIKE '%Caring Senior Service%'
      THEN 'Caring Senior Service'
      WHEN Name LIKE '%ComForCare%'
      THEN 'ComForCare Senior Services'
      WHEN Name LIKE '%Comfort Keepers%'
      THEN 'Comfort Keepers'
      WHEN Name LIKE 'Essential Care%'
      THEN 'Essential Care'
      WHEN Name LIKE '%FirstLight Home Care%'
      THEN 'First Light Home Care'
      WHEN Name LIKE '%First Light Home Care%'
      THEN 'First Light Home Care'
      WHEN Name LIKE '%FirstLight HomeCare%'
      THEN 'First Light Home Care'
      WHEN Name LIKE '%Girling Community Care%'
      THEN 'Kindred at Home'
      WHEN Name LIKE '%Home Care Assistance%'
      THEN 'The Key/Home Care Assistance'
      WHEN Name LIKE '%Home Helpers%'
      THEN 'Home Helpers'
      WHEN Name LIKE '%Home Instead%'
      THEN 'Home Instead'
      WHEN Name LIKE '%Home Matters Caregiving%'
      THEN 'Home Matters Caregiver'
      WHEN Name LIKE '%Homewatch Caregivers%'
      THEN 'Homewatch'
      WHEN Name LIKE '%Home watch Caregivers%'
      THEN 'Homewatch'
      WHEN Name LIKE '%HomeWell%'
      THEN 'HomeWell Care Services'
      WHEN Name LIKE '%Interim Healthcare%'
      THEN 'Interim Healthcare'
      WHEN Name LIKE '%Interim Health care%'
      THEN 'Interim Healthcare'
      WHEN Name LIKE '%Interim of Central Florida%'
      THEN 'Interim Healthcare'
      WHEN Name LIKE '%Kindred at Home%'
      THEN 'Kindred at Home'
      WHEN Name LIKE '%Kindred Homecare LLC%'
      THEN 'Kindred at Home'
      WHEN Name LIKE '%Nurse Next Door%'
      THEN 'Nurse Next Door'
      WHEN Name LIKE '%Options for Senior America%'
      THEN 'Options for Senior America'
      WHEN Name LIKE '%Prefered Care at Home%'
      THEN 'Preferred Care at Home'
      WHEN Name LIKE '%Preferred Care at Home%'
      THEN 'Preferred Care at Home'
      WHEN Name LIKE '%Preferred Care of West%'
      THEN 'Preferred Care at Home'
      WHEN Name LIKE '%Presidio Home Care%'
      THEN 'Presidio Home Care'
      WHEN Name LIKE '%Qualicare%'
      THEN 'Qualicare'
      WHEN Name LIKE '%Right at Home%'
      THEN 'Right at Home'
      WHEN Name LIKE '%Senior Helpers%'
      THEN 'Senior Helpers'
      WHEN Name LIKE '%SeniorBridge%'
      THEN 'SeniorBridge'
      WHEN Name LIKE '%Seniors Helping Seniors%'
      THEN 'Seniors Helping Seniors'
      WHEN Name LIKE '%SYNERGY Home Care%'
      THEN 'Synergy Home Care'
      WHEN Name LIKE '%Synergy Homecare%'
      THEN 'Synergy Home Care'
      WHEN Name LIKE '%Touching Hearts at Home%'
      THEN 'Touching Hearts at Home'
      WHEN Name LIKE '%Valley Home Care%'
      THEN 'Valley Home Care'
      WHEN Name LIKE '%Vesta Care%'
      THEN 'VestaCare'
      WHEN Name LIKE '%VestaCare%'
      THEN 'VestaCare'
      WHEN Name LIKE '%Visiting Angels%'
      THEN 'Visiting Angels'
      WHEN Name LIKE '%Your Choice Senior Care%'
      THEN 'Your Choice Senior Care'
      WHEN Name LIKE '%Baby Boomers In Home Companions%'
      THEN 'Baby Boomers In Home Companions'
      WHEN Name LIKE '%Bayada%'
      THEN 'Bayada'
      WHEN Name LIKE '%Care Assist%'
      THEN 'Care Assist'
      WHEN Name LIKE '%Care Indeed%'
      THEN 'Care Indeed'
      WHEN Name LIKE '%CareBuilders at Home%'
      THEN 'CareBuilders at Home'
      WHEN Name LIKE '%Elder Home Care%'
      THEN 'Elder Home Care'
      WHEN Name LIKE '%Family Matters%'
      THEN 'Family Matters'
      WHEN Name LIKE '%Friends of the Family%'
      THEN 'Friends of the Family'
      WHEN Name LIKE '%Golden Heart Senior Care%'
      THEN 'Golden Heart Senior Care'
      WHEN Name LIKE '%Granny Nannies%'
      THEN 'Granny Nannies'
      WHEN Name LIKE '%Griswold Home Care%'
      THEN 'Griswold Home Care'
      WHEN Name LIKE '%Griswold Care%'
      THEN 'Griswold Home Care'
      WHEN Name LIKE '%Home Care for the 21st Century%'
      THEN 'Home Care for the 21st Century'
      WHEN Name LIKE '%Homewatch%'
      THEN 'Homewatch'
      WHEN Name LIKE '%Home Care for the 21st Century%'
      THEN 'Home Care for the 21st Century'
      WHEN Name LIKE '%HomeCare Professionals%'
      THEN 'HomeCare Professionals'
      WHEN Name LIKE '%Just Like Family%'
      THEN 'Just Like Family'
      WHEN Name LIKE '%One You Love%'
      THEN 'One You Love'
      WHEN Name LIKE '%Royal Caregivers%'
      THEN 'Royal Caregivers'
      WHEN Name LIKE '%Spring Hills Home Care%'
      THEN 'Spring Hills Home Care'
      WHEN Name LIKE '%Superior Senior Care%'
      THEN 'Superior Senior Care'
      WHEN Name LIKE '%Talem Home Care%'
      THEN 'Talem Home Care'
      WHEN Name LIKE '%The Key%'
      THEN 'The Key/Home Care Assistance'
      WHEN Name LIKE '%TheKey%'
      THEN 'The Key/Home Care Assistance'
      WHEN Name LIKE '%Seniorcorp - Virigina Beach%'
      THEN 'The Key/Home Care Assistance'
      WHEN Name LIKE '%Victorian Home Care%'
      THEN 'Kindred at Home'
      WHEN Name LIKE '%Gentiva%'
      THEN 'Kindred at Home'
      WHEN Name LIKE '%VIP America%'
      THEN 'VIP America'
      WHEN Name LIKE '%Home Care for 21st Century of Sun City, FL%'
      THEN 'Home Care for the 21st Century'
      WHEN Name LIKE '%Preferred Care Home Health Care Of Cary, NC%'
      THEN 'Preferred Care at Home'
      ELSE NULL
    END AS Organization
  FROM prod_homecare_actransactional_organization.provider AS p
  LEFT JOIN prod_homecare_actransactional_homecare.referral AS r
    ON p.ProviderID = r.ProviderID
  WHERE
    r.ReferredOn >= '2023-01-01' AND NOT r.ProviderID IS NULL
) AS p
  ON p.OrgID = o.OrgID
WHERE
  NOT o.OrgID IS NULL
