-- Power BI query shape 88 of 663, from workspace_jf.landscape.qh.
-- Not a schema probe: this shape reads data and returns rows.
--
-- Executions            987
-- Distinct texts        2 (same query, different literals or projection)
-- Rows read             60,911,312
-- Rows returned         57,318
-- Avg duration          3,625 ms
-- Power BI datasets     3fdd5aed-f1c1-47e1-b7b0-5d4b81493a8d, 7d311f0f-60c1-430c-b0dc-ad78a0550d05, c65e1078-f986-4629-8d3f-50f7370b5719
-- Tables                prod_homecare_actransactional_homecare.referral, prod_homecare_actransactional_organization.org, prod_homecare_actransactional_organization.provider
--
-- Power BI's `SELECT ... FROM (...) AS `_`` envelope was stripped, so this
-- is the inner query as written, reformatted by sqlglot -- not the exact
-- bytes Power BI sent.

SELECT DISTINCT
  o.*
FROM prod_homecare_actransactional_organization.org AS o
RIGHT JOIN (
  SELECT DISTINCT
    p.*,
    CASE
      WHEN LOWER(name) LIKE '%123 home care%'
      THEN '123 Home Care'
      WHEN LOWER(name) LIKE '%1heart caregiver services%'
      THEN '1Heart Caregiver Services'
      WHEN LOWER(name) LIKE '%2nd family%'
      THEN '2nd Family'
      WHEN LOWER(name) LIKE '%a better solution%'
      THEN 'A Better Solution'
      WHEN LOWER(name) LIKE '%a homemade plan%'
      THEN 'A Homemade Plan'
      WHEN LOWER(name) LIKE '%acasa%'
      THEN 'Acasa'
      WHEN LOWER(name) LIKE '%advocate in-home care%'
      THEN 'Advocate In-Home Care'
      WHEN LOWER(name) LIKE '%age in place%'
      THEN 'Age in Place'
      WHEN LOWER(name) LIKE '%alegre home care%'
      THEN 'Alegre Home Care'
      WHEN LOWER(name) LIKE '%all ways caring%'
      THEN 'All Ways Caring'
      WHEN LOWER(name) LIKE '%24 hour home care%'
      THEN '24 Hour Home Care'
      WHEN LOWER(name) LIKE '%a caring hand services%'
      THEN 'A Caring Hand'
      WHEN LOWER(name) LIKE '%a hand to hold%'
      THEN 'A Hand to Hold'
      WHEN LOWER(name) LIKE '%a place at home%'
      THEN 'A Place at Home'
      WHEN LOWER(name) LIKE '%accentcare%'
      THEN 'AccentCare'
      WHEN LOWER(name) LIKE '%accordcare%'
      THEN 'AccordCare'
      WHEN LOWER(name) LIKE '%acti-kare%'
      THEN 'Acti-Kare'
      WHEN LOWER(name) LIKE '%acti kare%'
      THEN 'Acti-Kare'
      WHEN LOWER(name) LIKE '%advisacare%'
      THEN 'AdvisaCare'
      WHEN LOWER(name) LIKE '%addus home care%'
      THEN 'Addus Home Care'
      WHEN LOWER(name) LIKE '%affordable home care%'
      THEN 'Affordable Home Care'
      WHEN LOWER(name) LIKE '%affordable homecare%'
      THEN 'Affordable Home Care'
      WHEN LOWER(name) LIKE '%allegiant home care%'
      THEN 'Allegiant Home Care'
      WHEN LOWER(name) LIKE '%always best care %'
      THEN 'Always Best Care'
      WHEN LOWER(name) LIKE '%amada senior care%'
      THEN 'Amada Senior Care'
      WHEN LOWER(name) LIKE '%american in-home care%'
      THEN 'American In-Home Care'
      WHEN LOWER(name) LIKE '%americare%'
      THEN 'Americare'
      WHEN LOWER(name) LIKE '%arosa%'
      THEN 'Arosa'
      WHEN LOWER(name) LIKE '%assisting hands%'
      THEN 'Assisting Hands Home Care'
      WHEN LOWER(name) LIKE '%at home eldercare%'
      THEN 'At Home Eldercare'
      WHEN LOWER(name) LIKE '%bright star%'
      THEN 'BrightStar Care'
      WHEN LOWER(name) LIKE '%brightstar%'
      THEN 'BrightStar Care'
      WHEN LOWER(name) LIKE '%care advantage%'
      THEN 'Care Advantage'
      WHEN LOWER(name) LIKE '%caring senior service%'
      THEN 'Caring Senior Service'
      WHEN LOWER(name) LIKE '%comforcare%'
      THEN 'ComForCare Senior Services'
      WHEN LOWER(name) LIKE '%comfort keepers%'
      THEN 'Comfort Keepers'
      WHEN LOWER(name) LIKE 'essential care%'
      THEN 'Essential Care'
      WHEN LOWER(name) LIKE '%elara caring%'
      THEN 'Elara Caregiving'
      WHEN LOWER(name) LIKE '%firstlight home care%'
      THEN 'First Light Home Care'
      WHEN LOWER(name) LIKE '%first light home care%'
      THEN 'First Light Home Care'
      WHEN LOWER(name) LIKE '%firstlight homecare%'
      THEN 'First Light Home Care'
      WHEN LOWER(name) LIKE '%girling community care%'
      THEN 'Girling'
      WHEN LOWER(name) LIKE '%home care assistance%'
      THEN 'The Key/Home Care Assistance'
      WHEN LOWER(name) LIKE '%home helpers%'
      THEN 'Home Helpers'
      WHEN LOWER(name) LIKE '%home instead%'
      THEN 'Home Instead'
      WHEN LOWER(name) LIKE '%home matters caregiving%'
      THEN 'Home Matters Caregiver'
      WHEN LOWER(name) LIKE '%homewatch caregivers%'
      THEN 'Homewatch'
      WHEN LOWER(name) LIKE '%home watch caregivers%'
      THEN 'Homewatch'
      WHEN LOWER(name) LIKE '%homewell%'
      THEN 'HomeWell Care Services'
      WHEN LOWER(name) LIKE '%interim%'
      THEN 'Interim Healthcare'
      WHEN LOWER(name) LIKE '%interim%'
      THEN 'Interim Healthcare'
      WHEN LOWER(name) LIKE '%interim of central florida%'
      THEN 'Interim Healthcare'
      WHEN LOWER(name) LIKE '%kindred at home%'
      THEN 'Kindred at Home'
      WHEN LOWER(name) LIKE '%kindred homecare llc%'
      THEN 'Kindred at Home'
      WHEN LOWER(name) LIKE '%nurse next door%'
      THEN 'Nurse Next Door'
      WHEN LOWER(name) LIKE '%options for senior america%'
      THEN 'Options for Senior America'
      WHEN LOWER(name) LIKE '%prefered care at home%'
      THEN 'Preferred Care at Home'
      WHEN LOWER(name) LIKE '%preferred care at home%'
      THEN 'Preferred Care at Home'
      WHEN LOWER(name) LIKE '%preferred care of west%'
      THEN 'Preferred Care at Home'
      WHEN LOWER(name) LIKE '%presidio home care%'
      THEN 'Presidio Home Care'
      WHEN LOWER(name) LIKE '%qualicare%'
      THEN 'Qualicare'
      WHEN LOWER(name) LIKE '%right at home%'
      THEN 'Right at Home'
      WHEN LOWER(name) LIKE '%senior helpers%'
      THEN 'Senior Helpers'
      WHEN LOWER(name) LIKE '%seniorbridge%'
      THEN 'SeniorBridge'
      WHEN LOWER(name) LIKE '%seniors helping seniors%'
      THEN 'Seniors Helping Seniors'
      WHEN LOWER(name) LIKE '%synergy %'
      THEN 'Synergy Home Care'
      WHEN LOWER(name) LIKE '%synergy %'
      THEN 'Synergy Home Care'
      WHEN LOWER(name) LIKE '%touching hearts at home%'
      THEN 'Touching Hearts at Home'
      WHEN LOWER(name) LIKE '%valley home care%'
      THEN 'Valley Home Care'
      WHEN LOWER(name) LIKE '%vesta care%'
      THEN 'VestaCare'
      WHEN LOWER(name) LIKE '%vestacare%'
      THEN 'VestaCare'
      WHEN LOWER(name) LIKE '%visiting angels%'
      THEN 'Visiting Angels'
      WHEN LOWER(name) LIKE '%village care%'
      THEN 'Village Caregiving'
      WHEN LOWER(name) LIKE '%your choice senior care%'
      THEN 'Your Choice Senior Care'
      WHEN LOWER(name) LIKE '%baby boomers in home companions%'
      THEN 'Baby Boomers In Home Companions'
      WHEN LOWER(name) LIKE '%bayada%'
      THEN 'Bayada'
      WHEN LOWER(name) LIKE '%care assist%'
      THEN 'Care Assist'
      WHEN LOWER(name) LIKE '%care indeed%'
      THEN 'Care Indeed'
      WHEN LOWER(name) LIKE '%carebuilders at home%'
      THEN 'CareBuilders at Home'
      WHEN LOWER(name) LIKE '%elder home care%'
      THEN 'Elder Home Care'
      WHEN LOWER(name) LIKE '%family matters%'
      THEN 'Family Matters'
      WHEN LOWER(name) LIKE '%friends of the family%'
      THEN 'Friends of the Family'
      WHEN LOWER(name) LIKE '%golden heart senior care%'
      THEN 'Golden Heart Senior Care'
      WHEN LOWER(name) LIKE '%granny nannies%'
      THEN 'Granny Nannies'
      WHEN LOWER(name) LIKE '%griswold home care%'
      THEN 'Griswold Home Care'
      WHEN LOWER(name) LIKE '%home care for the 21st century%'
      THEN 'Home Care for the 21st Century'
      WHEN LOWER(name) LIKE '%homewatch%'
      THEN 'Homewatch'
      WHEN LOWER(name) LIKE '%home care for the 21st century%'
      THEN 'Home Care for the 21st Century'
      WHEN LOWER(name) LIKE '%homecare professionals%'
      THEN 'HomeCare Professionals'
      WHEN LOWER(name) LIKE '%just like family%'
      THEN 'Just Like Family'
      WHEN LOWER(name) LIKE '%one you love%'
      THEN 'One You Love'
      WHEN LOWER(name) LIKE '%royal caregivers%'
      THEN 'Royal Caregivers'
      WHEN LOWER(name) LIKE '%spring hills home care%'
      THEN 'Spring Hills Home Care'
      WHEN LOWER(name) LIKE '%superior senior care%'
      THEN 'Superior Senior Care'
      WHEN LOWER(name) LIKE '%talem home care%'
      THEN 'Talem Home Care'
      WHEN LOWER(name) LIKE '%the key%'
      THEN 'The Key/Home Care Assistance'
      WHEN LOWER(name) LIKE '%thekey%'
      THEN 'The Key/Home Care Assistance'
      WHEN LOWER(name) LIKE '%seniorcorp - virigina beach%'
      THEN 'The Key/Home Care Assistance'
      WHEN LOWER(name) LIKE '%victorian home care%'
      THEN 'Kindred at Home'
      WHEN LOWER(name) LIKE '%gentiva%'
      THEN 'Kindred at Home'
      WHEN LOWER(name) LIKE '%vip america%'
      THEN 'VIP America'
      WHEN LOWER(name) LIKE '%cornerstone caregiving%'
      THEN 'Cornerstone Caregiving'
      WHEN LOWER(name) LIKE '%innovage%'
      THEN 'Innovage PACE'
      WHEN ProviderOrganizationID = 126
      THEN 'LHC'
      ELSE NULL
    END AS Organization
  FROM prod_homecare_actransactional_organization.provider AS p
  LEFT JOIN prod_homecare_actransactional_homecare.referral AS r
    ON p.ProviderID = r.ProviderID
  WHERE
    r.referredon >= '2023-01-01' AND NOT r.providerid IS NULL
) AS p
  ON p.OrgID = o.OrgID
WHERE
  NOT o.OrgID IS NULL
